ScholarshipManagementSystem/Controllers/ApplyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Http;
using ScholarshipManagementSystem.Models;

namespace ScholarshipManagementSystem.Controllers
{
    [Authorize(Roles = "Student")]
    public class ApplyController : ApiController
    {
        private StudentContext db = new StudentContext();

        // GET api/Apply/?apply=
        public string GetApply(string apply)
        {
            if (apply == "Scholarship")
            {
                if (db.StudentInfoes.Find(User.Identity.Name).ApplyScholarship == true)
                {
                    return "取消申请奖学金";
                }
                else
                {
                    return "申请奖学金";
                }
            }
            else if (apply == "Grant")
            {
                if (db.StudentInfoes.Find(User.Identity.Name).ApplyGrant == true)
                {
                    return "取消申请助学金";
                }
                else
                {
                    return "申请助学金";
                }
            }
            else if (apply == "submitScholarship")
            {
                db.StudentInfoes.Find(User.Identity.Name).ApplyScholarship =
                    !db.StudentInfoes.Find(User.Identity.Name).ApplyScholarship;
                db.SaveChanges();
                return "";
            }
            else if (apply == "submitGrant")
            {
                db.StudentInfoes.Find(User.Identity.Name).ApplyGrant =
                    !db.StudentInfoes.Find(User.Identity.Name).ApplyGrant;
                db.SaveChanges();
                return "";
            }
            else
                return "Not Found.";
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ScholarshipManagementSystem/Controllers/BonusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Http;
using ScholarshipManagementSystem.Models;

namespace ScholarshipManagementSystem.Controllers
{
    [Authorize(Roles = "Student")]
    public class BonusController : ApiController
    {
        private StudentContext db = new StudentContext();

        // GET api/Bonus
        public List<BonusDTO> GetBonusTs()
        {
            List<BonusT> bonusts = db.BonusTs.Where(
                (p) => string.Equals(p.StudentInfoId, User.Identity.Name)).ToList();

            List<BonusDTO> bonusdtos = new List<BonusDTO>();
            for (int i = 0, j = bonusts.Count(); i < j; i++)
            {
                BonusDTO bdto = new BonusDTO();
                bdto.Id = bonusts[i].Id;
                bdto.Bonustype = bonusts[i].Bonustype;
                if (bonusts[i].Bonustype == BonusType.ProjectBonus)
                {
                    bdto.Date = bonusts[i].Date.ToShortDateString();
                    bdto.State = bonusts[i].Status;
                    bdto.Notes = bonusts[i].Notes;
                    BonusProject bb = new BonusProject();
                    bb = db.BonusProjects.Find(bonusts[i].DetailID);
                    if (bb != null)
                    {
                        bdto.Type = bb.Type;
                        bdto.Num = bb.Num;
                        bdto.Content = bb.Content;
                        // bdto.HName = bb.Name;
                        bdto.Score = bb.Score;
                    }
                }
                else if (bonusts[i].Bonustype == BonusType.PaperBonus)
                {
                    bdto.Date = bonusts[i].Date.ToShortDateString();
                    bdto.State = bonusts[i].Status;
                    bdto.Notes = bonusts[i].Notes;
                    BonusPaper bp = new BonusPaper();
                    bp = db.BonusPapers.Find(bonusts[i].DetailID);
                    if (bp != null)
                    {
                        bdto.Type = bp.Type;
                        bdto.Num = bp.Num;
                        bdto.Content = bp.Content;
                        bdto.Score = bp.Score;
                    }
                    int temp_id = bonusts[i].Id;
                    BonusPaperDetail bpd = db.BonusPaperDetails.SingleOrDefault((p) => (p.BelongedID == temp_id));
                    if (bpd != null)
                    {
                        bdto.Level = bpd.Level;
                        bdto.Way = bpd.Way;
                        bdto.HName = bpd.HName;
                        bdto.LName = bpd.LName;
                        bdto.Ranking = bpd.Ranking;
                    }
                }
                else if (bonusts[i].Bonustype == BonusType.CompetitionBonus)
                {
                    bdto.Date = bonusts[i].Date.ToShortDateString();
                    bdto.State = bonusts[i].Status;
                    bdto.Notes = bonusts[i].Notes;
                    BonusCompetition bc = new BonusCompetition();
                    bc = db.BonusCompetitions.Find(bonusts[i].DetailID);
                    if (bc != null)
                    {
                        bdto.Type = bc.Type;
                        bdto.Num = bc.Num;
                        bdto.Content = bc.Content;
                        bdto.Score = bc.Score;
                    }
                    int temp_id = bonusts[i].Id;
                    BonusCompetitionDetail bcd = db.BonusCompetitionDetails.SingleOrDefault((p) => (p.BelongedID == temp_id));
                    if (bcd != null)                        
                    {
                        bdto.Level = bcd.Level;
                        bdto.HName = bcd.HName;
                        bdto.LName = bcd.LName;
                        bdto.Ranking = bcd.Ranking;
                    }
                }
                bonusdtos.Add(bdto);
            }
           
            return bonusdtos;
        }

        // GET api/Bonus/5
        public BonusDTO GetBonusT(int id)
        {
            BonusT b = db.BonusTs.Find(id);
            if (b == null || b.StudentInfoId != User.Identity.Name) {
                throw new HttpResponseException(Request.CreateResponse(HttpStatusCode.NotFound));
            }

            BonusDTO bdto = new BonusDTO();
            bdto.Id = b.Id;
            bdto.Bonustype = b.Bonustype;
                if (b.Bonustype == BonusType.ProjectBonus)
                {
                    bdto.Date = b.Date.ToShortDateString();
                    bdto.State = b.Status;
                    bdto.Notes = b.Notes;
                    BonusProject bb = new BonusProject();
                    bb = db.BonusProjects.Find(b.DetailID);
                    if (bb != null)
                    {
                        bdto.Type = bb.Type;
                        bdto.Num = bb.Num;
                        bdto.Content = bb.Content;
                        // bdto.HName = bb.Name;
                        bdto.Score = bb.Score;
                    }
                }
                else if (b.Bonustype == BonusType.PaperBonus)
                {
                    bdto.Date = b.Date.ToShortDateString();
                    bdto.State = b.Status;
                    bdto.Notes = b.Notes;
                    BonusPaper bp = new BonusPaper();
                    bp = db.BonusPapers.Find(b.DetailID);
                    if (bp != null)
                    {
                        bdto.Type = bp.Type;
                        bdto.Num = bp.Num;
                        bdto.Content = bp.Content;
                        bdto.Score = bp.Score;
                    }
                    BonusPaperDetail bpd = new BonusPaperDetail();
                    bpd = db.BonusPaperDetails.SingleOrDefault((p) => (p.BelongedID == b.Id));
                    if (bpd != null)
                    {
                        bdto.Level = bpd.Level;
                        bdto.Way = bpd.Way;
                        bdto.HName = bpd.HName;
                        bdto.LName = bpd.LName;
                        bdto.Ranking = bpd.Ranking;
                    }
                }
                else if (b.Bonustype == BonusType.CompetitionBonus)
                {
                    bdto.Date = b.Date.ToShortDateString();
                    bdto.State = b.Status;
                    bdto.Notes = b.Notes;
                    BonusCompetition bc = new BonusCompetition();
                    bc = db.BonusCompetitions.Find(b.DetailID);
                    if (bc != null)
                    {
                        bdto.Type = bc.Type;
                        bdto.Num = bc.Num;
                        bdto.Content = bc.Content;
                        bdto.Score = bc.Score;
                    }
                    BonusCompetitionDetail bcd = new BonusCompetitionDetail();
                    bcd = db.BonusCompetitionDetails.SingleOrDefault((p) => (p.BelongedID == b.Id));
                    if (bcd != null)
                    {
                        bdto.Level = bcd.Level;
                        bdto.HName = bcd.HName;
                        bdto.LName = bcd.LName;
                        bdto.Ranking = bcd.Ranking;
                    }
                }
            return bdto;
        }

        // PUT api/Bonus/5
        public HttpResponseMessage PutBonusT(int id, BonusDTO bonusdto)
        {
            if (ModelState.IsValid && id == bonusdto.Id)
            {
                // check user and bonus.
                StudentInfo sinfo = db.StudentInfoes.Find(User.Identity.Name);
                if (sinfo == null)
                    return Request.CreateResponse(HttpStatusCode.NotFound);
                BonusT bonust = db.BonusTs.Find(id);
                if (bonust == null)
                    return Request.CreateResponse(HttpStatusCode.NotFound);
                if (bonust.StudentInfoId != sinfo.Id)
                    return Request.CreateResponse(HttpStatusCode.NotFound);

                bonust.Date = DateTime.Parse(bonusdto.Date);
                bonust.Notes = bonusdto.Notes;
                bonust.Status = "未审核";
                db.Entry(bonust).State = EntityState.Modified;
                try {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException ex) {
                    return Request.CreateResponse(HttpStatusCode.NotFound, ex);
                }
                return Request.CreateResponse(HttpStatusCode.OK);
            }
            return Request.CreateResponse(HttpStatusCode.BadRequest);
        }

        // POST api/Bonus
        public Int32 PostBonusT(BonusDTO bonusDTO)
        {
            int BonusNum = bonusDTO.Num;
            BonusT AddBonus = new BonusT();
            AddBonus.StudentInfoId = User.Identity.Name;
            AddBonus.Student = db.StudentInfoes.Find(AddBonus.StudentInfoId);
            AddBonus.Bonustype = CheckBonusType(BonusNum);
            AddBonus.DetailID = CheckID(BonusNum, AddBonus.Bonustype);
            AddBonus.Status = "未审核";
            AddBonus.Notes = "你的申报信息未填写完全，请点击编辑填写剩余信息！（信息补充完整后可删除本提示）";
            AddBonus.Date = DateTime.Now;

            try
            {
                if (AddBonus.Bonustype != BonusType.NoExistBonus)
                {
                    db.BonusTs.Add(AddBonus);
                    db.SaveChanges();
                    if (AddBonus.Bonustype == BonusType.CompetitionBonus)
                    {
                        BonusCompetitionDetail bcd = new BonusCompetitionDetail();
                        bcd.BelongedID = AddBonus.Id;
                        bcd.BelongedBonusT = AddBonus;
                        db.BonusCompetitionDetails.Add(bcd);
                        db.SaveChanges();
                    }

ScholarshipManagementSystem/Controllers/DeleteUserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Http;
using System.Web.Security;
using ScholarshipManagementSystem.Models;

namespace ScholarshipManagementSystem.Controllers
{
    [Authorize(Roles = "Teacher")]
    public class DeleteUserController : ApiController
    {
        private StudentContext db = new StudentContext();

        // DELETE api/DeleteUserFirst/5
        public HttpResponseMessage DeleteStudentInfo(string id)
        {
            StudentInfo studentinfo = db.StudentInfoes.Find(id);
            if (studentinfo == null)
            {
                return Request.CreateResponse(HttpStatusCode.NotFound);
            }

            // 删除班级打分中的全部记录
            {
                IEnumerable<ScoringT> s1 = db.ScoringTs.Where((p) => string.Equals(p.ScoringStudentInfoId, id));
                foreach (ScoringT s in s1)
                    db.ScoringTs.Remove(s);
                IEnumerable<ScoringT> s2 = db.ScoringTs.Where((p) => string.Equals(p.ScoredStudentInfoId, id));
                foreach (ScoringT s in s2)
                    db.ScoringTs.Remove(s);
            }
            // 将学生信息标记为注销
            studentinfo.Active = false;
            db.Entry(studentinfo).State = EntityState.Modified;

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException ex)
            {
                return Request.CreateErrorResponse(HttpStatusCode.NotFound, ex);
            }

            return Request.CreateResponse(HttpStatusCode.OK, studentinfo);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ScholarshipManagementSystem/Controllers/ExportForStudentInfoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Http;
using ScholarshipManagementSystem.Models;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;
using System.IO;

namespace ScholarshipManagementSystem.Controllers
{
    [Authorize(Roles = "Teacher")]
    public class ExportForStudentInfoController : ApiController
    {
        private StudentContext db = new StudentContext();

        // GET api/ExportForStudentInfo/?Name=&classId=&studentId=
        public List<StudentInfo> GetStudentInfoes(String Name, String classId, String studentId)
        {
            if (Name != null)
            {
                return db.StudentInfoes.Where(s => (s.Name.Contains(Name))).ToList();
            }
            else if (classId != null)
            {
                return db.StudentInfoes.Where(s => (s.ClassId.Contains(classId))).ToList();
            }
            else if (studentId != null)
            {
                return db.StudentInfoes.Where(s => (s.Id.Contains(studentId))).ToList();
            }
            else
            {
                return db.StudentInfoes.ToList();
            }
        }

        // GET api/ExportForStudentInfo/?method=&Name=&classId=&studentId=
        public String GetExportScoringTs(String method, String Name, String classId, String studentId)
        {
            try
            {
                if (method == "export")
                {
                    IWorkbook workbook = new XSSFWorkbook();
                    ISheet sheet1 = workbook.CreateSheet("学生信息");
                    IRow row = sheet1.CreateRow(0);
                    row.CreateCell(0).SetCellValue("学号");
                    row.CreateCell(1).SetCellValue("姓名");
                    row.CreateCell(2).SetCellValue("班级");
                    row.CreateCell(3).SetCellValue("奖学金申请");
                    row.CreateCell(4).SetCellValue("助学金申请");
                    row.CreateCell(5).SetCellValue("班级打分提交");
                    row.CreateCell(6).SetCellValue("评选资格");

                    List<StudentInfo> sis = GetStudentInfoes(Name, classId, studentId);
                    StudentInfo si = new StudentInfo();
                    int i = 1, j = sis.Count(), k = 0;
                    for (; k < j; k++, i++)
                    {
                        row = sheet1.CreateRow(i);
                        si = sis[k];
                        row.CreateCell(0).SetCellValue(si.Id.ToString());
                        row.CreateCell(1).SetCellValue(si.Name.ToString());
                        row.CreateCell(2).SetCellValue(si.ClassId.ToString());
                        row.CreateCell(3).SetCellValue(si.ApplyScholarship.ToString());
                        row.CreateCell(4).SetCellValue(si.ApplyGrant.ToString());
                        row.CreateCell(5).SetCellValue(si.SubmitScoring.ToString());
                        row.CreateCell(6).SetCellValue(si.Qualification.ToString());
                    }

                    String filePath = System.Web.HttpContext.Current.Server.MapPath("~/App_Export/");
                    filePath += "StudentInfoSimple.xlsx";
                    FileStream sw = File.Create(filePath);
                    workbook.Write(sw);
                    sw.Close();
                    return "Success";
                }
                else
                {
                    return "Error : Not Found.";
                }
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ScholarshipManagementSystem/Views/Home/BonusCompetitionEdit.cshtml
@{
    Layout = null;
}

<h2 style="font-family:Microsoft YaHei;text-align:center">比赛加分项编辑</h2>

<div class="msg-div" style="font-family:Microsoft YaHei;">
    <link rel=stylesheet type="text/css" href="/Content/Scoring.css">
    <p>　竞赛等级：<input id="Level" type="text" name="Level" /></p>
    <p>　竞赛名称：<input id="HName" type="text" name="HName" /></p>
    <p>　项目名称：<input id="LName" type="text" name="LName" /></p>
    <p>　获奖等级：<input id="Ranking" type="text" name="Ranking" /></p>
    <p>　项目内容：<input id="Content" type="text" name="Content" /></p>
    <p>　获奖时间：<input id="Date" type="text" name="Date" onclick="openDatepicker()" onkeydown="openDatepicker()" /></p>
    <div id="datepicker"></div>
    <p>　备注信息：<input id="Notes" type="text" name="Notes" /></p>
    <p style="font-family:Microsoft YaHei;text-align:center;color:green;">编辑后请删除默认的备注信息。</p>
    <div style="text-align:center;">
        <input class="uploadButton" type="button" name="submitButton" onclick="submitDate()" value="确定" />
        <input class="uploadButton" type="button" name="deleteButton" onclick="deleteDate()" value="删除" />
        <input class="uploadButton" type="button" name="closeButton" onclick="closeWindow()" value="取消" />
    </div>
</div>

<script type="text/javascript" src="/Scripts/jquery-1.8.2.js"></script>

<link rel="stylesheet" href="/Content/jquery-ui-1.10.3.start/css/start/jquery-ui-1.10.3.custom.css" >
<script src="/Content/jquery-ui-1.10.3.start/js/jquery-1.9.1.js"></script>
<script src="/Content/jquery-ui-1.10.3.start/js/jquery-ui-1.10.3.custom.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        var apiUrl = '@ViewBag.ApiUrl';
        var id = '@ViewBag.Id'
        $.getJSON(apiUrl + '/' + id, function (data) {
            $('#Date').val(data.Date);
            $('#Notes').val(data.Notes);
            var detailUrl = '/api/BonusCompetitionDetail/' + data.Id;
            $.getJSON(detailUrl, function (detail_data) {
                $('#Level').val(detail_data.Level);
                $('#LName').val(detail_data.LName);
                $('#HName').val(detail_data.HName);
                $('#Ranking').val(detail_data.Ranking);
                $('#Content').val(detail_data.Content);
            });
        });
    })

    function openDatepicker() {
        $("#datepicker").datepicker("dialog", null,
            function (selectDate) { $("#Date").val(selectDate); }
        );
    }

    function submitDate() {
        var apiUrl = '@ViewBag.ApiUrl';
        var id = '@ViewBag.Id'
        var detailUrl = '/api/BonusCompetitionDetail';
        $.getJSON(apiUrl + '/' + id, function (data) {
            $.getJSON(detailUrl + '/' + data.Id, function (detail_data) {
                if ($("#Date").val() == "") {
                    alert('请填写获奖日期！');
                    return false;
                }

                data.Date = $("#Date").val();
                data.Notes = $("#Notes").val();
                $.ajax({
                    url: apiUrl + '/' + data.Id,
                    type: 'PUT',
                    data: data,
                    error: function () { alert('提交失败，请重新尝试！'); },
                    success: function () {
                        detail_data.Level = $('#Level').val();
                        detail_data.LName = $('#LName').val();
                        detail_data.HName = $('#HName').val();
                        detail_data.Ranking = $('#Ranking').val();
                        detail_data.Content = $('#Content').val();
                        $.ajax({
                            url: detailUrl + '/' + detail_data.Id,
                            type: 'PUT',
                            data: detail_data,
                            error: function () { alert('提交失败，请重新尝试！'); },
                            success: function () {
                                window.opener.history.go(0);
                                window.close();
                            }
                        });
                    }
                }); 
            });
        });
    }

    function deleteDate() {
        $.ajax({
            url: '@ViewBag.ApiUrl' + '/' + '@ViewBag.Id',
            type: 'DELETE',
            error: function () { alert('删除失败！'); },
            success: function () {
                alert("删除成功！");
                window.opener.history.go(0);
                window.close();
            }
        });
        return true;
    }

    function closeWindow() {
        window.opener = null;
        window.close();
    }
</script>

ScholarshipManagementSystem/Views/Home/Student.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
   <meta charset="utf-8" />
   <!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame -->
   <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
   <!-- Mobile viewport optimized: h5bp.com/viewport -->
   <meta name="viewport" content="width=device-width">

   <title>学生 - 主页</title>

   <link rel="stylesheet" type="text/css" href="../Scripts/BootMetro/css/bootmetro.css">
   <link rel="stylesheet" type="text/css" href="../Scripts/BootMetro/css/bootmetro-responsive.css">
   <link rel="stylesheet" type="text/css" href="../Scripts/BootMetro/css/bootmetro-icons.css">
   <link rel="stylesheet" type="text/css" href="../Scripts/BootMetro/css/bootmetro-ui-light.css">
   <link rel="stylesheet" type="text/css" href="../Scripts/BootMetro/css/datepicker.css">
   <script src="../Scripts/BootMetro/js/modernizr-2.6.2.min.js"></script>
</head>

<body style="font-family:Microsoft YaHei;"><!--background-color:#C7EDCC;-->
    <div id="wrap">
        <!-- Header -->
        <div id="nav-bar" class="">
         <div class="pull-left">
            <div id="header-container">
               <h1 style="font-family:Microsoft YaHei">软件学院奖学金管理系统</h1>
               <div class="dropdown">
                  <a class="header-dropdown dropdown-toggle accent-color" data-toggle="dropdown" href="#">
                     功能列表
                     <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                      <li>@Html.ActionLink("奖（助）学金申请", "Apply", "Home")</li>
                      <li>@Html.ActionLink("班级打分", "Scoring", "Home")</li>
                      <li>@Html.ActionLink("加分项申报", "Bonus", "Home")</li>
                  </ul>
            </div>
            </div>
         </div>
         <div class="pull-right">
            <div id="top-info" class="pull-right"> 
                欢迎使用 , @Html.ActionLink(User.Identity.Name, "Manage", "Account", routeValues: null, htmlAttributes: new { @class = "username", title = "Manage" })。
                @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" })) {
                    @Html.AntiForgeryToken()
                    <a href="javascript:document.getElementById('logoutForm').submit()">退出系统</a>
                }
            </div>
         </div>
      </div>
   
        <!-- Body -->
        <div class="metro panorama">
            <div class="panorama-sections">
                <div class="panorama-section">
                    <h2>　</h2>
                    <div class="tile-column-span-2">
                        <a class="tile widepeek" href="Apply">
                            <div class="image-wrapper">
                                <span class="icon icon-user"></span>
                            </div>
                            <div class="tile wide text">
                                <div class="text-header">奖(助)学金申请</div>
                                <div class="text-header"></div>
                                <div class="text4">自主申请奖学金、助学金。默认均为不申请，想要申请奖、助学金请先来此处提交申请意向。</div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="panorama-section">
                    <h2>　</h2>
                    <div class="tile-column-span-2">
                        <a class="tile widepeek bg-color-orange" href="Scoring">
                            <div class="image-wrapper">
                                <span class="icon icon-feed"></span>
                            </div>
                            <div class="tile wide text bg-color-orange">
                                <div class="text-header">班级打分</div>
                                <div class="text4">班级内部互相打分.</div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="panorama-section">
                    <h2>　</h2>
                    <div class="tile-column-span-2">
                        <a class="tile widepeek bg-color-gray" href="Bonus">
                            <div class="image-wrapper">
                                <span class="icon icon-wrench"></span>
                            </div>
                            <div class="tile wide text bg-color-gray">
                                <div class="text-header">加分项申报</div>
                                <div class="text4">提交、查看自己的加分项情况.</div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="panorama-section">
                    <h2>　</h2>
                    <div class="tile-column-span-2">
                        <a class="tile widepeek bg-color-red" href="BonusList">
                            <div class="image-wrapper">
                                <span class="icon icon-cog"></span>
                            </div>
                            <div class="tile wide text bg-color-red">
                                <div class="text-header">奖励项目列表</div>
                                <div class="text4">查看软件学院学生综合测评奖励项目，</div>
                                <div class="text4">寻找属于自己的加分项.</div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    <a id="panorama-scroll-prev" href="#"></a>
    <a id="panorama-scroll-next" href="#"></a>
    <div id="panorama-scroll-prev-bkg"></div>
    <div id="panorama-scroll-next-bkg"></div>
   </div>

    <div style="font-family:Microsoft YaHei;text-align:center">
        <div>
            <p>推荐使用 Google Chrome 或者 Mozilla Firefox 浏览器。请不要使用360系列浏览器。</p>
            <h4>&copy; @DateTime.Now.Year - 上海交通大学软件学院</h4>
            <h4>&copy; @DateTime.Now.Year - School of Software, Shanghai Jiao Tong University.</h4>
        </div>
    </div>

   <!-- Grab Google CDN's jQuery. fall back to local if necessary -->
   <script src="//code.jquery.com/jquery-1.10.0.min.js"></script>
   <script>window.jQuery || document.write("<script src='../Scripts/BootMetro/js/jquery-1.10.0.min.js'>\x3C/script>")</script>

   <script type="text/javascript" src="../Scripts/BootMetro/js/min/bootstrap.min.js"></script>
   <script type="text/javascript" src="../Scripts/BootMetro/js/bootmetro-panorama.js"></script>
   <script type="text/javascript" src="../Scripts/BootMetro/js/bootmetro-pivot.js"></script>
   <script type="text/javascript" src="../Scripts/BootMetro/js/bootmetro-charms.js"></script>
   <script type="text/javascript" src="../Scripts/BootMetro/js/bootstrap-datepicker.js"></script>

   <script type="text/javascript" src="../Scripts/BootMetro/js/jquery.mousewheel.min.js"></script>
   <script type="text/javascript" src="../Scripts/BootMetro/js/jquery.touchSwipe.min.js"></script>
    
    <script type="text/javascript">
       $('.panorama').panorama({
           showscrollbuttons: true,
           keyboard: true,
           parallax: true
       });
       $('#pivot').pivot();
   </script>

</body>
</html>